spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dll-auto: validate
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/typeracer'
    username: root
    password: toor


server:
  port: 8080
